### ISSUE TITLE
List projects not working

### ISSUE THREAD

**Issue by bholagabbar** [wolfbeacon/wolfbeacon-ops#2]
`@wb-deployment-bot list projects`  should list the available projects @junthehacker

**Comment by junzhengca** [comment]
Fixing on branch [list-projects](https://github.com/wolfbeacon/wolfbeacon-infra-ops/tree/list-projects).

**Comment by junzhengca** [comment]
Fixed with pull request [#3](https://github.com/wolfbeacon/wolfbeacon-infra-ops/pull/3)
